### ISSUE TITLE
ExternalSecret CRD needs to choose where the secret will end up in

### ISSUE THREAD

**Issue by knelasevero** [ContainerSolutions/externalsecret-operator#106]
As per https://github.com/godaddy/kubernetes-external-secrets/pull/477/files

Right now we only support secrets ending up being k8s-secrets in the end (we can continue only supporting that, but as per the common CRD, we need to have a target field in our ExternalSecret resource that would only accept `target: secret`)

**Describe the solution you'd like**
Right now the default final destination for a secret is a normal kubernetes secret. The idea here is to have other destinations like another secret manager.

**What is the added value?**
Even if we don't implement the actual sink, we can comply with the common CRD.

**Give us examples of the outcome**

```
apiVersion: external-secrets.k8s.io/v1alpha1
kind: ExternalSecret
metadata:
  name: foo
spec:
  storeRef:
    kind: SecretStore # ClusterSecretStore
    name: my-store
  # target field to define where secrets will end up
  target:
    secret:
      name: my-secret
      template:
        type: kubernetes.io/TLS
  data:
    key: value
```

**Constraints:**
