### ISSUE TITLE
Introduce documentation for each backend implementation

### ISSUE THREAD

**Issue by riccardomc** [ContainerSolutions/externalsecret-operator#24]
We need a consistent way to specify instructions and parameters documentation for each type of backend. We could restructure the `secrets` directory to contain a sub-directory for each backend with a README.md in it For example:
```
pkg/secrets/
  asm/
     asm.go
     asm_test.go
     README.md
  onepassword/
     onepassword.go
     onepassword_test.go
     README.md
...
```

And the README.md would look like something like:

### Format
```yaml
Type: "asm"
Name: "asm-example"
Parameters:
    accessKeyID: ""
    region: ""
    secretAccessKey: ""
```

### Parameters
| Parameter | Description | Required | Default
| - | - | - | -
| `accessKeyID` | AWS Access Key ID that can talk to AWS Secrets Manager | yes | `""` 
| `region` | AWS Region | yes | `""`
| `secretAccessKey` | AWS Secret Access Key corresponding to `accessKeyID` | yes | `""`
