### ISSUE TITLE
Gitlab Backend

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/externalsecret-operator#90]
For an internal application I currently have to write `gitlab-ci.yaml` code to copy secrets from Gitlab into Kubernetes. If there is a Gitlab backend for the ESO these secrets can be synced automatically and they can be managed via the Gitlab UI.

**Describe the solution you'd like**
Support gilab CI variables/secrets as a backend for our external secret.

**What is the added value?**
Having new backends increases chances for adoption and broadens the operator use cases. Gitlab is used by us, but some clients, and it is also nice to have kind of a pull strategy instead of pushing secrets into the cluster.

**Give us examples of the outcome**

```

apiVersion: store.externalsecret-operator.container-solutions.com/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  controller: staging
  # Sample store types
  #
  # Gitlab  
  store:
    type: gitlab
    auth: 
      secretRef: 
        name: externalsecret-operator-credentials-gitlab
        namespace: externalsecret-operator-system
    parameters:
#### TODO: not sure about parameters here. Please update who takes this on so we can discuss further
#### ...
```

**Observations (Constraints, Context, etc):**
