### ISSUE TITLE
Support more keys and values per secret

### ISSUE THREAD

**Issue by knelasevero** [ContainerSolutions/externalsecret-operator#92]
Related to #7. Also related to https://github.com/godaddy/kubernetes-external-secrets/pull/477 since we want to move in the new CRD direction, at least for this obvious good things. 

**Describe the solution you'd like**
We would like to have multiple keys defined in the ExternalSecret, and end up with a kubernetes secret with multiple keys and values.

**What is the added value?**
We group multiple secrets that make sense to be together in one kubernetes secret.

**Give us examples of the outcome**
ExternalSecret:
```
apiVersion: secrets.externalsecret-operator.container-solutions.com/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret-sample-2
spec:
  store_ref: 
    name: externalsecret-operator-secretstore-sample-2
    namespace: externalsecret-operator-system
  secrets:
    - key: operator-secret
      version: latest
    - key: operator-encrypted
      version: latest
```
Kubernetes Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name:  externalsecret-sample-2
type: Opaque
data:
  operator-secret: <base64 value>
  operator-encrypted: <base64 value>
```

**Constraints:**

Limit secrets in ExternalSecret to reasonable number (to avoid misuse).
